### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by someatoms** [HarpMedia/Facebook-RSVP-iCal#1]
Hey! Was looking into building this myself. Have you made any progress?

**Comment by SeanBannister** [comment]
omg, can't believe this repo still exists :) no I didn't start the project unfortunately. But certainly interested if you make any progress.

**Comment by someatoms** [comment]
Haha, the internet never forgets or something like that I suppose. I created a basic app know that basically does what you intended this one to be I suppose. Check it out at [eventcal.flown.io](eventcal.flown.io) or here on [github](https://github.com/someatoms/eventcal).

**Comment by SeanBannister** [comment]
Nice one :) just started using it. time for me to delete this repo.
